### PR TITLE
Update temporal operators

### LINKED ISSUE #533: CQL: Consider renaming anyinteracts to tintersects
If there is no strong requirement to leave CQL unchanged, consider renaming `anyinteracts` to `tintersects`, as the current name does not seem to carry its meaning of intersecting time, and will just confuse everyone.

### LINKED ISSUE #565: CQL: instant-interval and instant-instant relations
Regarding the following in 9.3. Requirements Class "Enhanced Temporal Operators":

> CQL supports date and timestamps as time instants, but even the smallest "instant" has a duration and can also be evaluated as an interval. For the purposes of determining the temporal relationship between two temporal expressions, an instant is treated as the interval from the beginning to the end of the instant. The following diagram illustrates the meaning of the temporal operators.

Yes, time is continuous, which means that any moment of time can be divided into an infinite number of smaller moments. But, time is _measured_ by dividing time into time intervals with a specific duration (temporal resolution = granularity). In practice, a time interval whose duration is less than the temporal resolution used is _considered to be_ an instant.

So to take example 15: when using a temporal resolution of one second, 1969-07-20T20:17:40Z is treated as an [instant](https://www.w3.org/TR/owl-time/#time:Instant) (although we know that we can subdivide it in fractions of seconds, but that is not the resolution used in this case) and 1969-07-16T13:32:00Z/1969-07-24T16:50:35Z is an interval.

The [Time Ontology](https://www.w3.org/TR/owl-time/), listed as a reference, also makes a distinction between instants and time intervals.

As a minimum, the "TOVERLAPS" and "OVERLAPPEDBY" relations are only meaningful for interval-interval relations, not for instant-interval or instant-instant relations. So how should a server react when the client submits a query containing `1969-07-20T20:17:40Z TOVERLAPS 1969-07-16T13:32:00Z/1969-07-24T16:50:35Z`? That query is not meaningful. Should an error code be returned?

How about https://www.w3.org/TR/owl-time/#time:hasBeginning and https://www.w3.org/TR/owl-time/#time:hasEnd? They have time:Instant as range and are conceptually similar to https://www.w3.org/TR/owl-time/#time:intervalStarts and https://www.w3.org/TR/owl-time/#time:intervalFinishes. BEGINS is mapped to time:intervalStarts, but a time interval has a start instant.

### LINKED ISSUE #570: CQL: usefulness of the current Simple CQL regarding temporal predicates
I am wondering how useful the current Simple CQL requirements class is regarding temporal predicates, as the only relationship supported is `ANYINTERACTS`. I understand that implementing all relationships from Allen's interval algebra is too much, but, as also argued in #565, I think that a distinction should be made between

- instant-instant relations
- instant-interval relations
- interval-interval relations

I would like to suggest including instant-instant relations in Simple CQL, i.e. supporting before, equals and after for instants. Isn't it the case that any other relation involving intervals actually can be expressed by comparing their start and end instants?

### PR DESCRIPTION
**Pull request by cportele**
* closes #565 (except the rebranding to CQL2 -> open a new issue when merging this PR)
* closes #570
* closes #533 
* addresses #562 (only temporal operators)
* addresses #532 (only temporal operators)

### CODE REVIEW

**Comment by cportele** [comment]
@heidivanparys - please have a look at the changes

**Review by pvretano — APPROVED** [review]

**Comment by pvretano** [comment]
@cportele looks good.  Merge if you like ...

**Comment by cportele** [comment]
@pvretano - thanks, let's see, if @heidivanparys has any comments on the changes

**Comment by heidivanparys** [comment]
@cportele 
Has there been a misunderstanding regarding #570?

I added a commit to illustrate what I meant with "I would like to suggest including instant-instant relations in Simple CQL, i.e. supporting before, equals and after for instants.": https://github.com/heidivanparys/ogcapi-features/commit/cd6a6fa9d064a79b34492056990b3b4b0751de94

Would that be possible, especially if #483 would be accepted (only instants expressed in UTC allowed)? That way, behaviour would be similar to that of relational databases, where <, = and > can be used to compare instants, allowing to form more complex expressions on the client side.

**Comment by cportele** [comment]
> Has there been a misunderstanding regarding #570?

I think/hope what is in the PR is what is documented as the approach documented during the meting (see https://github.com/opengeospatial/ogcapi-features/issues/565#issuecomment-826884331), but we can discuss.

Also note that it was decided to move anyinteracts (or t_intersects) from Simple CQL to the other temporal operators, see #532.

**Comment by cportele** [comment]
Meeting 2021-06-14: We should include a discussion of date or date-time handling in Simple CQL when we discuss the comparison operators like `<` or `>` (including in the ATS). This should work with SQL backends, but will it create issues for NoSQL backends (MongoDB, Couchbase, ElasticSearch, GQL, GraphQL, etc). @pvretano will investigate. If others would like that other backends should be considered, let us know here. Note there does not have to be a one-to-one mapping, there will always be parsing and processing involved.

**Pull request merged**
