### PR TITLE
Simplify the LIKE operator

### PR DESCRIPTION
**Pull request by pvretano**
- Simplify the LIKE operator by removing the WILDCARD, SINGLECHAR, ESCAPECHAR, and NOCASE qualifiers.
- Add the builtin functions UPPER() and LOWER() to allow caseless comparisons.

### CODE REVIEW

**Comment by pvretano** [comment]
Question:  Right now I have simplified the LIKE expression quite a bit.  I only define the wildcard character (%) and the escape character (\).  Is this too simple?  Show we let the RHS of the LIKE operator be a regex? ... maybe regex is too complex?

**Review by cportele — COMMENTED** [review]
Thanks @pvretano. Two questions for discussion:

* We did discuss regex before, but decided against it, see #489. However, I thought that we would keep "_" as the single char wildcard since this is what LIKE does. Did we decide against it? I agree, the general wildcard "%" is more important, but I think that users of LIKE would expect support for "_", too?
* UPPER/LOWER are now special cases in the BNF grammar, not two pre-defined functions. Wouldn't pre-defined functions be cleaner?

**Comment by pvretano** [comment]
- @cportele oh, I thought we decided to strip it right down BUT I agree the single char wildcard would be useful.  I can't tell what character you are proposing for the single char match.  It looks like double quotes on my screen but I would propose we use the underbar "_".
- I'm not sure what you mean by "pre-defined" in this context.  Do you mean that the function are not built into the grammar the way the spatial operators are and instead we simply document that two functions need to be implemented named upper/lower and described their prototypes using the syntax defined in the grammar?

**Comment by cportele** [comment]
> I can't tell what character you are proposing for the single char match. It looks like double quotes on my screen but I would propose we use the underbar "_".

Oops, yes, I meant the underscore char. I forgot this is for italics in markdown...

> I'm not sure what you mean by "pre-defined" in this context. Do you mean that the functions are not built into the grammar the way the spatial operators are and instead we simply document that two functions need to be implemented named upper/lower and described their prototypes using the syntax defined in the grammar?

Yes. But I also see the point that the spatial operators are also functions that we have in the grammar. I think we also need to consider how we will handle #546 in the BNF in this context. Let's discuss that in the meeting today or next week.

**Comment by cportele** [comment]
See https://github.com/opengeospatial/ogcapi-features/issues/541#issuecomment-860830350

**Pull request merged**
