### PR TITLE
Fixes for #828

### PR DESCRIPTION
**Pull request by jerstlouis**

### CODE REVIEW

**Comment by jerstlouis** [comment]
@pvretano @cportele

**Comment by cportele** [comment]
Meeting 2023-05-22: @cportele and @pvretano to review, more reviews are welcome, too!

**Review by cportele — APPROVED** [review]
The PR implements the changes agreed in https://github.com/opengeospatial/ogcapi-features/issues/828#issuecomment-1538453680. It goes beyond that an in addition it also classifies the former spatial/temporal/array operators as spatial/temporal/array *relation* functions (the use of "relation" was not part of the previous decision), but I guess with a view to a future extension beyond filter expressions the use of "relation" makes sense.

**Comment by cportele** [comment]
Meeting 2023-06-19: @pvretano will review today. If approved, we can merge the PR:

**Review by pvretano — CHANGES_REQUESTED** [review]
The meaning of the term "relation" is very context dependent.  For example, in databases a "relation" exists between two database tables when one table has a foreign key that references the primary key of the other table.  Because of this I would say we should be careful how we use the term.
I would prefer that we just stick with "functions" ... "spatial functions", "array functions", "temporal functions", etc.

**Comment by jerstlouis** [comment]
@pvretano Yes the relation is context dependent, but here a context is given: _spatial relation_ functions, _array relation_ functions.

If we just say "spatial functions", then I would expect to find a centroid or buffer calculation in there, so it seems too general.

"Relation" is the standard mathematics term to describe what all of these functions do:

https://en.wikipedia.org/wiki/Relation_(mathematics)

Yes, "relation" is also use in Databases with that other meaning:

https://en.wikipedia.org/wiki/Relation_(database)

But wouldn't you agree that here from the context, it is obvious which meaning is intended?

**Comment by cportele** [comment]
Meeting 2023-07-03: It is just a terminology issue and has no impact on CQL2 as a language. Since there is no consensus on changing the previous decision we will stick to it and not use "relation function", just "function". We will make the change and then merge.

**Pull request merged**
