### PR TITLE
Review of part 4

### PR DESCRIPTION
**Pull request by cportele**
This pull requests includes the following changes:

- editorial updates
- changes to align the document with parts 1 to 3 and to meet OGC documentation requirements
- changes to make the requirements more precise, in particular in the features requirements class
- address #292 and #476 (the URIs of the schema requests need a discussion)

Link to HTML: http://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-features/blob/part4-cp/extensions/transactions/simple/standard/20-002.html

### CODE REVIEW

**Review by pvretano — APPROVED** [review]
@cportele looks really good!  You can go ahead and merge ... or I can do it if you prefer.

**Comment by cportele** [comment]
Thanks @pvretano - We can quickly go through the PR in the SWG meeting today and see, if there are other questions or comments, before we merge.

**Review by pvretano — APPROVED** [review]
@cportele looks good.  I'm good with merging at your convenince.

**Comment by cportele** [comment]
Thanks @pvretano.

Merged as agreed during the SWG meeting on 2021-02-01.

**Pull request merged**
